In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("weather_data/cities.csv")

In [3]:
df

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Rain,snow
0,0,Boden,SE,2020-07-12 21:38:16,65.83,21.69,57.20,87,100,8.05,0.00,0
1,0,Mar del Plata,AR,2020-07-12 21:35:46,-38.00,-57.56,45.00,52,20,17.22,0.00,0
2,0,Nantucket,US,2020-07-12 21:37:30,41.28,-70.10,80.01,78,1,14.99,0.00,0
3,0,Ushuaia,AR,2020-07-12 21:38:17,-54.80,-68.30,35.60,93,40,18.34,0.00,0
4,0,Cape Town,ZA,2020-07-12 21:34:09,-33.93,18.42,57.99,76,75,29.97,1.52,0
...,...,...,...,...,...,...,...,...,...,...,...,...
572,0,Ashta,IN,2020-07-12 21:39:48,23.02,76.72,78.44,83,100,8.61,0.00,0
573,0,Bardstown,US,2020-07-12 21:39:35,37.81,-85.47,78.80,69,40,4.47,0.25,0
574,0,Pāvilosta,LV,2020-07-12 21:39:48,56.89,21.19,55.40,93,39,3.36,0.00,0
575,0,Margate,GB,2020-07-12 21:39:48,51.38,1.39,59.00,70,71,1.01,0.00,0
576,0,Pamplona,ES,2020-07-12 21:39:48,42.82,-1.64,68.00,82,40,9.17,0.00,0

In [4]:
min_temp = 0 
max_temp = 0
rain_input = ""
snow_input = ""

min_temp = input("what min tempreature would you like?")
max_temp = input("what max tempreature would you like?")
rain_input = input("do want it to be raining?")
snow_input = input("do want it to be snowing?")

what min tempreature would you like?65
what max tempreature would you like?75
do want it to be raining?No
do want it to be snowing?No

In [5]:
print (snow_input)
print (rain_input)

No
No

In [6]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [7]:
print (g_key)

AIzaSyCoENkI968YQMcd37Um7Rs5t98GzXl5dgE

In [8]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Rain,snow
0,0,Boden,SE,2020-07-12 21:38:16,65.83,21.69,57.20,87,100,8.05,0.00,0
1,0,Mar del Plata,AR,2020-07-12 21:35:46,-38.00,-57.56,45.00,52,20,17.22,0.00,0
2,0,Nantucket,US,2020-07-12 21:37:30,41.28,-70.10,80.01,78,1,14.99,0.00,0
3,0,Ushuaia,AR,2020-07-12 21:38:17,-54.80,-68.30,35.60,93,40,18.34,0.00,0
4,0,Cape Town,ZA,2020-07-12 21:34:09,-33.93,18.42,57.99,76,75,29.97,1.52,0

In [9]:
# Configure gmaps to use your Google API key.
print (gmaps.configure(api_key=g_key))

None

In [10]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure()
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
display (fig)

Figure(layout=FigureLayout(height='420px'))

In [11]:
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp)

In [12]:
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

In [13]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [14]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 65
What is the maximum temperature you would like for your trip? 75

In [15]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Rain,snow
7,0,Ponta do Sol,PT,2020-07-12 21:38:17,32.67,-17.10,70.00,75,0,3.83,0.00,0
10,0,Kathmandu,NP,2020-07-12 21:36:55,27.72,85.32,69.80,94,75,3.36,0.00,0
13,0,Jamestown,US,2020-07-12 21:37:17,42.10,-79.24,73.99,68,1,9.17,0.00,0
14,0,São Mateus,BR,2020-07-12 21:38:18,-18.72,-39.86,69.67,80,11,5.12,0.00,0
15,0,Sturgeon Falls,CA,2020-07-12 21:38:18,46.36,-79.93,68.00,68,90,11.41,0.00,0
19,0,São Filipe,CV,2020-07-12 21:37:58,14.90,-24.50,74.57,79,63,4.54,0.00,0
21,0,Marawi,PH,2020-07-12 21:38:15,8.00,124.29,73.00,91,100,5.99,0.00,0
27,0,Saint-Philippe,RE,2020-07-12 21:38:20,-21.36,55.77,66.20,68,31,4.70,0.75,0
33,0,Ouadda,CF,2020-07-12 21:38:21,8.08,22.40,69.31,90,93,1.23,0.51,0
39,0,Palora,EC,2020-07-12 21:38:23,-1.70,-77.93,74.50,88,36,1.39,0.81,0

In [16]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

              City Country  Max Temp    Lat     Lng Hotel Name
7     Ponta do Sol      PT     70.00  32.67  -17.10
10       Kathmandu      NP     69.80  27.72   85.32
13       Jamestown      US     73.99  42.10  -79.24
14      São Mateus      BR     69.67 -18.72  -39.86
15  Sturgeon Falls      CA     68.00  46.36  -79.93
19      São Filipe      CV     74.57  14.90  -24.50
21          Marawi      PH     73.00   8.00  124.29
27  Saint-Philippe      RE     66.20 -21.36   55.77
33          Ouadda      CF     69.31   8.08   22.40
39          Palora      EC     74.50  -1.70  -77.93

In [18]:
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [19]:
# Set the parameters to search for a hotel in Paris.
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key,
    "location": "48.8566, 2.3522"}
# Use base URL to search for hotels in Paris.
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
# Make request and get the JSON data from the search.
hotels = requests.get(base_url, params=params).json()
hotels

{'html_attributions': [],
 'next_page_token': 'CqQCHAEAALfqzB-oJafPOk-73A-B18T-2AfWZ92RReph7-b8P2AfTri0VzJYmMfGfzgZRjdBrxEJWxnYIMPND5G7W0V_DGy0l5frKvHUbe0KuXw6oR9ad-YVReiu96iQtvxAnkyLdKkkTtW_xyix0GNdAREU4GZz3K3bZePWjBVPu3waLSMnlp7EQQgeHm1gc1nc2S790cIsRVC_qaDvby-otzdTWBgw7CzslJ_YGF4RCWafJTv_Yd4-8LQdSx-juiSu4GT3nWJ-PWEEdZiavS8RtOgsteNfUeufhC6Hx3MP-13B5v7TjYRdaxqlMi5Btg6PHNGo34QmUM8H7ikXrnzgLrQG4ezANZ80KImhI__hbbaUyDZVxnNfIWTSps8pfREKOtHzAhIQ59hZeY_2aPQ0ufNmYMocURoUWl6pzyw1CmZ4KglCflyG-1sPJTM',
 'results': [{'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8581126, 'lng': 2.3529277},
    'viewport': {'northeast': {'lat': 48.8594393802915,
      'lng': 2.354352980291502},
     'southwest': {'lat': 48.8567414197085, 'lng': 2.351655019708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': '7fa47cb61d7345cecc3b802d0e04fcff2b3d5ecb',
   'name': 'Hôtel Duo',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3840,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/107554201425443337224">Hôtel Duo</a>'],
     'photo_reference': 'CmRaAAAAC_c_eXGQkSwYVGtr0mohZSoLyKy6sqf0mfgYpunEqZPC2QMFLE_HSQnTqW8x-VQTH82-JPcYyjbMxRxOIyVAVgA6hcvVxGxJb4OsBETGYFc82_jRgnCemLNmOIr8SrwiEhC-RPM1s27n2NoSk0Z-g8NjGhT4O7OjKPyCp90IgYe7h6C3JdXMYw',
     'width': 5760}],
   'place_id': 'ChIJWU9CqB1u5kcR5P1F2SMoJmc',
   'plus_code': {'compound_code': 'V953+65 Paris, France',
    'global_code': '8FW4V953+65'},
   'rating': 4.2,
   'reference': 'ChIJWU9CqB1u5kcR5P1F2SMoJmc',
   'scope': 'GOOGLE',
   'types': ['night_club',
    'spa',
    'lodging',
    'bar',
    'gym',
    'health',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 266,
   'vicinity': '11 Rue du Temple, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8582861, 'lng': 2.3464944},
    'viewport': {'northeast': {'lat': 48.8595495802915,
      'lng': 2.347780980291502},
     'southwest': {'lat': 48.8568516197085, 'lng': 2.345083019708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': '4d2e3fa9d12bf9feb685e628eaa4da9b180956a9',
   'name': 'Hôtel Britannique - Paris Louvre',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1426,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108984000175492464929">Hôtel Britannique - Paris Louvre</a>'],
     'photo_reference': 'CmRaAAAA98MzDrlZZCOO5jgyKbcGNSVOfOP1AjcuCkp5tFGA4gIfqvhTME1ZkyM5KShn7vafliExeOtTxELzprV_Va5bwc_4zVyVqUaaj9hjOiP3-MQUA8Z142KZ804fSSE7Lx16EhA31YhA5maE_ukRucjbjXjHGhQv_WKV5mDZGrGIuEhs_g77SgBu-g',
     'width': 1476}],
   'place_id': 'ChIJ-4Siox9u5kcRm9vM6DcMXyU',
   'plus_code': {'compound_code': 'V85W+8H Paris, France',
    'global_code': '8FW4V85W+8H'},
   'rating': 4.5,
   'reference': 'ChIJ-4Siox9u5kcRm9vM6DcMXyU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 263,
   'vicinity': '20 Avenue Victoria, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8606655, 'lng': 2.3469293},
    'viewport': {'northeast': {'lat': 48.8618387802915,
      'lng': 2.348475730291502},
     'southwest': {'lat': 48.85914081970851, 'lng': 2.345777769708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': '9f68a76d7e95a1f94ca131a0511bfe5ffa306818',
   'name': 'Citadines Les Halles Paris (Apart Hotel Paris)',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 496,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102565262508115704337">Citadines Les Halles Paris (Apart Hotel Paris)</a>'],
     'photo_reference': 'CmRaAAAAZ3oUu3JCbN7gZr__Pb_9zrKXlPKPwBgYygZsKozM5OLvMsuM0lJpUPvU5CuJeTUY5n_KkGLcWCWZRYhcffSpuMZBNo5YCPAcJ5ts5cqRgzWZbnc8fZQs38EhfgRnMLutEhAccROSomXFN3UjzOY80ZViGhQyfH1Zy4Lpb93kh01Grs3N8DniHw',
     'width': 745}],
   'place_id': 'ChIJQ_QDrxhu5kcRJzNxLLEOSfU',
   'plus_code': {'compound_code': 'V86W+7Q Paris, France',
    'global_code': '8FW4V86W+7Q'},
   'rating': 4.1,
   'reference': 'ChIJQ_QDrxhu5kcRJzNxLLEOSfU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 796,
   'vicinity': '4 Rue des Innocents, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8607769, 'lng': 2.3463217},
    'viewport': {'northeast': {'lat': 48.8620135802915,
      'lng': 2.347597080291502},
     'southwest': {'lat': 48.8593156197085, 'lng': 2.344899119708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': 'd0fde78ef5688caa69780be22af2ec83d4adfd32',
   'name': 'Novotel Paris Les Halles',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2000,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/111815616573299411056">Novotel Paris Les Halles</a>'],
     'photo_reference': 'CmRaAAAAx4HWoR_uXWYR_0h7hOfc5n3PDY-AQ53UB27fFFllXgMpOGgvnOlQfnhlFseIc4jGom8weO0jXKjOSMjgNoZlCi1B6OYrbjVRLJpXPjL0CAiDQXjbhgo0HTWGJbwq9EPbEhAqIEjDIdLOod1IjQX4amPGGhS0hJnLvhkFjfJf9Uc_tI55GBU2xQ',
     'width': 3000}],
   'place_id': 'ChIJGW2pNx9u5kcRI3oyL8NG5BQ',
   'plus_code': {'compound_code': 'V86W+8G Paris, France',
    'global_code': '8FW4V86W+8G'},
   'rating': 4.4,
   'reference': 'ChIJGW2pNx9u5kcRI3oyL8NG5BQ',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 2015,
   'vicinity': '8 Place Marguerite de Navarre, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.86034799999999, 'lng': 2.344054},
    'viewport': {'northeast': {'lat': 48.8616503302915,
      'lng': 2.345521080291502},
     'southwest': {'lat': 48.8589523697085, 'lng': 2.342823119708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': '071875f44126b9c8284f24b598fdfce0ef2b15a8',
   'name': 'Hôtel Ducs de Bourgogne',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1842,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/101411638353598558320">Best Western Premier Ducs de Bourgogne</a>'],
     'photo_reference': 'CmRaAAAAnBI8VBJJGq1wCJ2v0SkhLMCT-29XOpeWdl2dCfO4jgvzBH677D3837XSFLTkiRTAva-Thz98LSBL1vPR-PWYBjgP_SFtpKsawTLdX4QtCpOTnuX7oPaUo3pXoFyVudxgEhA6m-K8ZAprdB1SbJtBUvjGGhSyMF1os5Tma5L1eqqPqcfsj3Zf3g',
     'width': 2880}],
   'place_id': 'ChIJifTG5yFu5kcRdnisbwxnAx4',
   'plus_code': {'compound_code': 'V86V+4J Paris, France',
    'global_code': '8FW4V86V+4J'},
   'rating': 4.5,
   'reference': 'ChIJifTG5yFu5kcRdnisbwxnAx4',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 265,
   'vicinity': '19 Rue du Pont Neuf, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8555091, 'lng': 2.3408736},
    'viewport': {'northeast': {'lat': 48.8569130802915,
      'lng': 2.342311480291502},
     'southwest': {'lat': 48.8542151197085, 'lng': 2.339613519708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': 'da46237a58939495edf652bdf976bd44df477f05',
   'name': 'Citadines Saint-Germain-des-Prés Paris',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3024,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/116649065792056265685">Gilsun LEE</a>'],
     'photo_reference': 'CmRaAAAAYlIeEAfpJ8lxEHjc7m_H7FgzRDL-G_QOw3IhgY6HsKoUGJru15XfXAOyb4AjcNyJykfV9CAIdjGZF6EeB5AYiWO_JYrJbYtlPN9Fuk7fc7YoLUHqX2CjBOvvLFptjyOuEhC46PwI28BXm70aREdZLRwHGhQUzT6tImkXMznawz7ZTBeWb32BFg',
     'width': 4032}],
   'place_id': 'ChIJo5pYcN9x5kcRERXdocMgqmE',
   'plus_code': {'compound_code': 'V84R+68 Paris, France',
    'global_code': '8FW4V84R+68'},
   'rating': 4.3,
   'reference': 'ChIJo5pYcN9x5kcRERXdocMgqmE',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 637,
   'vicinity': '53 ter Quai des Grands Augustins, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.86634659999999, 'lng': 2.36064},
    'viewport': {'northeast': {'lat': 48.8677623302915,
      'lng': 2.361952180291502},
     'southwest': {'lat': 48.86506436970851, 'lng': 2.359254219708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': '87ab2d184ee12f6be846d60470ed800629c99521',
   'name': 'Paris France Hôtel',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2673,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102332962500946068613">Paris France Hôtel</a>'],
     'photo_reference': 'CmRaAAAAlhO07LgP4TrOr_i4Pp-MMOz9Qyn9LiZfKeB_FbLDgQpg-jJrAV0agPagRQoswox4iZCcWWk-2c6ECKC8VtD7o0QhZz4TzCNR1YBk-CfSSfNi6wbDTRQsBDTZqN6ArBw9EhCgTpNzPrI_znehw7oi6cRyGhQV8clf2YqpIB93Iwvesfxb04ziaw',
     'width': 3463}],
   'place_id': 'ChIJhXWLZg9u5kcRDVyqoZYgcmg',
   'plus_code': {'compound_code': 'V986+G7 Paris, France',
    'global_code': '8FW4V986+G7'},
   'rating': 4.3,
   'reference': 'ChIJhXWLZg9u5kcRDVyqoZYgcmg',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 366,
   'vicinity': '72 Rue de Turbigo, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8549629, 'lng': 2.3331998},
    'viewport': {'northeast': {'lat': 48.8563280302915,
      'lng': 2.334478630291502},
     'southwest': {'lat': 48.8536300697085, 'lng': 2.331780669708499}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': 'd466793620469a720b439cf769a6f4c28217ef88',
   'name': 'Hôtel Bel Ami',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 4377,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/111426311500153571368">Hôtel Bel Ami</a>'],
     'photo_reference': 'CmRaAAAA7pTsMvqc7JYkwbkuqHyLU6TmHV-Rl1RGfldVHIcYPtOAXEInDaH7mg0wHsSL2ykilcCF4vW6o6LiTqgVF0nFboIlHFeV22tRlmMpMF9pxyK70jyaOOhc9xzy1nDucSbQEhDxDwvztLx8bZF2_nscNgl4GhRa69u_VePCsn7IjEGujPd_JRoERA',
     'width': 6566}],
   'place_id': 'ChIJj0jPiddx5kcRnYv-p3-vfCA',
   'plus_code': {'compound_code': 'V83M+X7 Paris, France',
    'global_code': '8FW4V83M+X7'},
   'rating': 4.6,
   'reference': 'ChIJj0jPiddx5kcRnYv-p3-vfCA',
   'scope': 'GOOGLE',
   'types': ['spa',
    'lodging',
    'bar',
    'restaurant',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 447,
   'vicinity': '7 Rue Saint-Benoît, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.86386539999999, 'lng': 2.3325488},
    'viewport': {'northeast': {'lat': 48.8652309302915,
      'lng': 2.333762030291502},
     'southwest': {'lat': 48.8625329697085, 'lng': 2.331064069708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': '20dd8ae8d6ad9bbbe4ea9c6caf623fa071be187f',
   'name': 'Hotel Regina Louvre',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2828,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/109066439891801774697">Hôtel Regina Louvre</a>'],
     'photo_reference': 'CmRaAAAA2fonEET0Ur_syR_D-z2BbC7d25HqGVc9EJpTcD-NtoBHyQPTMbnE4Opnye6PBtqS1eGeb50IHb_BJIxOuTYfeIZtOPcu_BXGG0RYeD2FYR4sxHp1QaJMra8VeruL-cuMEhAavAUcly8us18XCX7rb69ZGhQNV2POJNxWYF0niYOS-ChwQaj8og',
     'width': 4242}],
   'place_id': 'ChIJP_-HCS9u5kcRsj9b1x7Pl8w',
   'plus_code': {'compound_code': 'V87M+G2 Paris, France',
    'global_code': '8FW4V87M+G2'},
   'rating': 4.5,
   'reference': 'ChIJP_-HCS9u5kcRsj9b1x7Pl8w',
   'scope': 'GOOGLE',
   'types': ['lodging',
    'bar',
    'restaurant',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 495,
   'vicinity': '2 Place des Pyramides, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.84795229999999, 'lng': 2.370869},
    'viewport': {'northeast': {'lat': 48.84922153029149,
      'lng': 2.372321980291502},
     'southwest': {'lat': 48.84652356970849, 'lng': 2.369624019708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': '6662d8cf04aa119625278786b9a8b5042c30409c',
   'name': 'ibis Paris Gare de Lyon Ledru Rollin 12ème',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 4128,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/101379513086988207219">T Lovely</a>'],
     'photo_reference': 'CmRaAAAAbbQuvoSTUUK2cemo3xW5jrtGHZafRdy2T3vldVjhsUUI3kohLuL8osLulX_9qcXGv5H-jnUG1CLRq-zH9ms0fpBgPF8T1ITOmBL_5IUoMQKOBvML-_zs-UbCZyxD0FnFEhDbD7ZACbvUg5P5CBeCtaHyGhSFUApgb7yRKWkBZN2vtZBYaprfgA',
     'width': 2322}],
   'place_id': 'ChIJ9RNxcQNy5kcRnZJ4vsuXcow',
   'plus_code': {'compound_code': 'R9XC+58 Paris, France',
    'global_code': '8FW4R9XC+58'},
   'rating': 4,
   'reference': 'ChIJ9RNxcQNy5kcRnZJ4vsuXcow',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 727,
   'vicinity': '41/43 Avenue Ledru-Rollin, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8475464, 'lng': 2.3718722},
    'viewport': {'northeast': {'lat': 48.8488750302915,
      'lng': 2.373125480291502},
     'southwest': {'lat': 48.8461770697085, 'lng': 2.370427519708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': 'dd8abb1bc4b1337fc3bd3f26e92d36c9a31de2fd',
   'name': 'Hôtel De France Gare de Lyon Bastille',
   'photos': [{'height': 3264,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/113588055173738079547">Boris Diaz castillo</a>'],
     'photo_reference': 'CmRaAAAAHDpv0q3vxhaWZcMuVCheWjq1jIAqiKBdQIYRdKmNQBY7zDIRFhiI9uprX9br2YjmbV05hCyo4jjd2Hwqz7j1daCBXZcbbBQ6sbkzaTDDcVb6fXilvAObztybAtNJjVhYEhA-LtnpEjxKBNRkYE_seWc6GhRuTjYvf9A-k9PQB8gvFVAdS4ATOQ',
     'width': 2448}],
   'place_id': 'ChIJz6DBYgNy5kcRhOu1LhDIECM',
   'plus_code': {'compound_code': 'R9XC+2P Paris, France',
    'global_code': '8FW4R9XC+2P'},
   'rating': 3.3,
   'reference': 'ChIJz6DBYgNy5kcRhOu1LhDIECM',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 374,
   'vicinity': '12 Rue de Lyon, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8717386, 'lng': 2.3447052},
    'viewport': {'northeast': {'lat': 48.8731394302915,
      'lng': 2.346067130291502},
     'southwest': {'lat': 48.8704414697085, 'lng': 2.343369169708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': '78d0f620a6cdf990371302f25505f3916839f53a',
   'name': 'Hôtel Corona Opéra',
   'photos': [{'height': 3024,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/105311226083684825186">福山慎一</a>'],
     'photo_reference': 'CmRaAAAAsTbTeKhnriTG4Sqli0nryfofjA4ZRFyfTYnk8ywp7qU9rOGWTnLWNIG28E8OSHzwnnp7I0gpIaBAPFKV3Evdtv5JHmd0mcnwEkZojAa-nM30G4xaUhCudqZWghkSx2MREhBjD-KmocumoW-Tk0LG-urUGhRRQuzQ81WMIjmQhCKGlI1luVok3Q',
     'width': 4032}],
   'place_id': 'ChIJ8e3Qcj5u5kcR2MIGwNxustk',
   'plus_code': {'compound_code': 'V8CV+MV Paris, France',
    'global_code': '8FW4V8CV+MV'},
   'rating': 4,
   'reference': 'ChIJ8e3Qcj5u5kcR2MIGwNxustk',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 301,
   'vicinity': '8 Cité Bergère, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8423491, 'lng': 2.3632246},
    'viewport': {'northeast': {'lat': 48.84365308029151,
      'lng': 2.364707180291502},
     'southwest': {'lat': 48.84095511970851, 'lng': 2.362009219708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': 'c2c8e3f55bda0fd2bec95cd85db83c756bfebe2c',
   'name': 'Hôtel Libertel Austerlitz Jardin des Plantes',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 683,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/113748802076686483057">Hôtel Libertel Austerlitz Jardin des Plantes</a>'],
     'photo_reference': 'CmRaAAAA67HERDrUO2U1bGAXXDDv4C5glF2-uerMpwgy2gNdF_r3EartgTro9_lxsqVvtBwr0e2p1A0WQtYiUaV2AL3EMU2iIV0OZ8_VsDHbmXA8qT_hKrfzjpBk9j607FH4vzLoEhB0Yil_Q7EPIiKmS5E25WixGhR5VRTscpopLbRRFbJdjgSo2tWboQ',
     'width': 1024}],
   'place_id': 'ChIJe-udXPZx5kcRKURHNFv5BSw',
   'plus_code': {'compound_code': 'R9R7+W7 Paris, France',
    'global_code': '8FW4R9R7+W7'},
   'rating': 3.9,
   'reference': 'ChIJe-udXPZx5kcRKURHNFv5BSw',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 416,
   'vicinity': "12 Boulevard de l'Hôpital, Paris"},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.864294, 'lng': 2.3307997},
    'viewport': {'northeast': {'lat': 48.8655898302915,
      'lng': 2.332108780291502},
     'southwest': {'lat': 48.8628918697085, 'lng': 2.329410819708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': '50797fba20cc1e735c57820607b18b04abf162b9',
   'name': 'Saint James Albany Paris Hôtel Spa',
   'photos': [{'height': 650,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108570400659068256718">Saint James Albany Paris Hôtel Spa</a>'],
     'photo_reference': 'CmRaAAAAJSLYLFQ2edNyzTFAtsTEvXYjTOYStsvieVy9kRXTIoPbgzELRrBBMgzdnLh27sERLfDsD_8qU1mcqOhg05C4bBJXKw4wpJQeFoig6JLy3oPUr_YtiLED560B2d3NlrHlEhBfTHU_r8gwL9vUXvR9CJF-GhT6ZKxX7Vi0o7SOpfOU2q7jQ0k-gA',
     'width': 802}],
   'place_id': 'ChIJ8znTVS5u5kcREq8TmzOICFs',
   'plus_code': {'compound_code': 'V87J+P8 Paris, France',
    'global_code': '8FW4V87J+P8'},
   'rating': 4,
   'reference': 'ChIJ8znTVS5u5kcREq8TmzOICFs',
   'scope': 'GOOGLE',
   'types': ['spa',
    'lodging',
    'bar',
    'restaurant',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 1065,
   'vicinity': '202 Rue de Rivoli, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.87110329999999, 'lng': 2.3389728},
    'viewport': {'northeast': {'lat': 48.8724296802915,
      'lng': 2.340311330291502},
     'southwest': {'lat': 48.8697317197085, 'lng': 2.337613369708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': 'ef15575a5c2adf57431313a0af490a78350630a5',
   'name': 'Hôtel Icône',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1066,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108137830440312077288">Hôtel Icône</a>'],
     'photo_reference': 'CmRaAAAAE7dB1MsF1ib76OMUCsyzV9ADGQb8JrXLE8g_Qj-QzVolrNoKvQuSQotC13UZ25QnEwLKRndOX4-wkCjMx6z2wZjKwP63L9u21fBs0bcTiz8_vvu8c8lzu6eVTgD4-GUpEhBFscjWB7sqMOb7ujrvKF5UGhTzomkO5QYr-buMGs7fLRhxHdIkRQ',
     'width': 1600}],
   'place_id': 'ChIJpQvq5Dtu5kcR0COam2f7v_I',
   'plus_code': {'compound_code': 'V8CQ+CH Paris, France',
    'global_code': '8FW4V8CQ+CH'},
   'rating': 3.7,
   'reference': 'ChIJpQvq5Dtu5kcR0COam2f7v_I',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 133,
   'vicinity': "4 Rue d'Amboise, Paris"},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8654924, 'lng': 2.3271121},
    'viewport': {'northeast': {'lat': 48.8667867302915,
      'lng': 2.328593580291502},
     'southwest': {'lat': 48.8640887697085, 'lng': 2.325895619708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': '751a05ec173f53ba581d8a32e047a69302c4886c',
   'name': 'The Westin Paris - Vendôme',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1366,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/110604580348447711691">The Westin Paris - Vendôme</a>'],

In [20]:
hotels["results"][4]["name"]

'Hôtel Ducs de Bourgogne'

In [21]:
# Iterate through the DataFrame.
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key,
    "location": "48.8566, 2.3522"}

for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [22]:
hotel_df

,City,Country,Max Temp,Lat,Lng,Hotel Name
7,Ponta do Sol,PT,70.00,32.67,-17.10,Hotel do Campo
10,Kathmandu,NP,69.80,27.72,85.32,Hotel Shanker Kathmandu
13,Jamestown,US,73.99,42.10,-79.24,Hampton Inn & Suites Jamestown
14,São Mateus,BR,69.67,-18.72,-39.86,Hotel Rio Norte
15,Sturgeon Falls,CA,68.00,46.36,-79.93,Lincoln Motel
...,...,...,...,...,...,...
564,Sloboda,RU,65.43,51.14,40.30,
565,Muros,ES,72.00,42.78,-9.06,Apartment Av. Castelao
566,Saurimo,AO,66.67,-9.66,20.39,Hotel Kawissa Saurimo
569,La Rochelle,FR,68.00,46.17,-1.15,Hôtel Saint Jean d'Acre
576,Pamplona,ES,68.00,42.82,-1.64,Hotel Albret

In [23]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [24]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

In [25]:
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [26]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [27]:
# Create the output file (CSV).
output_data_file = "weather_data/WeatherPy_vacation.csv"
# Export the City_Data into a CSV.
hotel_df.to_csv(output_data_file)