In [1]:
import pandas as pd
df = pd.read_csv("weather_data/WeatherPy_vacation.csv")

In [2]:
df.groupby(["Country"]).count()

         Unnamed: 0  City  Max Temp  Lat  Lng  Hotel Name
Country
AF                1     1         1    1    1           0
AL                2     2         2    2    2           2
AO                4     4         4    4    4           4
AR                1     1         1    1    1           1
BR                7     7         7    7    7           7
CA                6     6         6    6    6           6
CD                5     5         5    5    5           2
CF                7     7         7    7    7           0
CG                1     1         1    1    1           1
CI                5     5         5    5    5           5
CL                2     2         2    2    2           2
CM                1     1         1    1    1           1
CN                2     2         2    2    2           2
CV                1     1         1    1    1           1
EC                1     1         1    1    1           1
ES                8     8         8    8    8           8
FR                4     4         4    4    4           4
GA                5     5         5    5    5           4
GE                1     1         1    1    1           1
GN                1     1         1    1    1           0
GR                1     1         1    1    1           0
ID                1     1         1    1    1           1
IN                1     1         1    1    1           1
IR                1     1         1    1    1           1
IT                1     1         1    1    1           1
KZ                1     1         1    1    1           1
LR                2     2         2    2    2           2
MA                1     1         1    1    1           1
MG                7     7         7    7    7           6
MU                5     5         5    5    5           5
MZ                3     3         3    3    3           3
NG                4     4         4    4    4           3
NP                2     2         2    2    2           2
PE                1     1         1    1    1           1
PH                1     1         1    1    1           1
PK                1     1         1    1    1           1
PT                7     7         7    7    7           7
RE                2     2         2    2    2           2
RU               14    14        14   14   14           6
SL                2     2         2    2    2           0
SO                1     1         1    1    1           1
SS                1     1         1    1    1           0
TD                1     1         1    1    1           0
TR                1     1         1    1    1           1
TZ                1     1         1    1    1           0
UA                1     1         1    1    1           1
US                2     2         2    2    2           2
UZ                1     1         1    1    1           1
VE                1     1         1    1    1           1
ZA                1     1         1    1    1           1

In [3]:
Country_CA = df.loc[df["Country"] =="CA"][:4]
Country_CA

,Unnamed: 0,City,Country,Max Temp,Lat,Lng,Hotel Name
4,15,Sturgeon Falls,CA,68.00,46.36,-79.93,Lincoln Motel
17,94,Sault Ste. Marie,CA,66.20,46.52,-84.33,Comfort Inn
64,311,Halifax,CA,73.99,44.65,-63.57,Hotel Halifax
87,392,Kirkland Lake,CA,66.20,48.14,-80.04,Comfort Inn

In [4]:
Country_CA.iloc[0:4]["Lng"]

4    -79.93
17   -84.33
64   -63.57
87   -80.04
Name: Lng, dtype: float64

In [5]:
import gmaps
import gmaps.datasets
from config import g_key
gmaps.configure(api_key=g_key)

# Latitude-longitude pairs
North_Bay = (46.32, -79.47)
Torbay = (47.67, -52.73)
Sept_Iles = (50.20, -66.38)
Havre_St_Pierre = (50.23, -63.60)

fig = gmaps.figure()
North_Bay2Havre_St_Pierre = gmaps.directions_layer(North_Bay, Havre_St_Pierre)
fig.add_layer(North_Bay2Havre_St_Pierre)
fig

Figure(layout=FigureLayout(height='420px'))

In [6]:
fig = gmaps.figure()
North_Bay2Havre_St_Pierre = gmaps.directions_layer(
        North_Bay, Havre_St_Pierre,
        travel_mode='DRIVING')
fig.add_layer(North_Bay2Havre_St_Pierre)
fig

Figure(layout=FigureLayout(height='420px'))

In [7]:
fig = gmaps.figure()
North_Bay2Havre_St_Pierre = gmaps.directions_layer(
        North_Bay, Havre_St_Pierre,
        travel_mode='BICYCLING')
fig.add_layer(North_Bay2Havre_St_Pierre)
fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
fig = gmaps.figure()
North_Bay2Havre_St_Pierre = gmaps.directions_layer(
        North_Bay, Havre_St_Pierre,
        travel_mode='WALKING')
fig.add_layer(North_Bay2Havre_St_Pierre)
fig

Figure(layout=FigureLayout(height='420px'))

In [11]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = Country_CA_df[["Lat", "Lng"]]
max_temp = Country_CA_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

NameError: name 'Country_CA_df' is not defined